M48
; DRILL file {KiCad 9.0.7} date 2026-01-28T11:34:08-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-28T11:34:08-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
%
G90
G05
T1
X24.62Y-43.45
X41.8Y-43.4
T2
X33.2Y-40.8
X33.2Y-47.8
M30
